name:                implicit-effects
version:             0.1.0.0
synopsis:            Demo effects

license:             BSD-3-Clause
license-file:        LICENSE
author:              Soares Chen
maintainer:          soares.chen@maybevoid.com

ghc-options:
  -Wall -O2

dependencies:
  - base ^>=4.12.0.0 && < 5
  - mtl
  - stm
  - free
  - comonad
  - transformers
  - natural-transformation

default-extensions:
  - GADTs
  - Strict
  - StrictData
  - RankNTypes
  - TypeFamilies
  - InstanceSigs
  - DeriveFunctor
  - TypeOperators
  - ImplicitParams
  - ExplicitForAll
  - KindSignatures
  - ConstraintKinds
  - TypeApplications
  - FlexibleContexts
  - FlexibleInstances
  - OverloadedStrings
  - DerivingStrategies
  - AllowAmbiguousTypes
  - ScopedTypeVariables
  - MultiParamTypeClasses
  - GeneralizedNewtypeDeriving

library:
  source-dirs:  src/lib

executables:
  implicit-effects-demo:
    main:          Main.hs
    source-dirs:   src/main
    dependencies:
      - implicit-effects

  implicit-effects-benchmark:
    main:          Main.hs
    source-dirs:   src/benchmark
    dependencies:
      - implicit-effects
      - criterion

tests:
  implicit-effects-test:
    main:           Main.hs
    source-dirs:    src/test
    dependencies:
      - implicit-effects
      - tasty
      - QuickCheck
      - tasty-hunit
      - tasty-quickcheck